[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
              _reward and {n=G.UIT.R, config={align = "cm"}, nodes={
                {n=G.UIT.T, config={text = localize('ph_blind_reward'), scale = 0.35, colour = disabled and G.C.UI.TEXT_INACTIVE or G.C.WHITE, shadow = not disabled}},
                {n=G.UIT.T, config={text = string.rep(localize("$"), blind_choice.config.dollars)..'+', scale = 0.35, colour = disabled and G.C.UI.TEXT_INACTIVE or G.C.MONEY, shadow = not disabled}}
              }} or nil,
'''
position = "after"
payload = '''
  {n=G.UIT.R, config={align = "cm"}, nodes={
                {n=G.UIT.T, config={text = localize('k_event'), scale = 0.3, colour = disabled and G.C.UI.TEXT_INACTIVE or G.C.WHITE, shadow = not disabled}},
                {n=G.UIT.T, config={text = G.GAME.sajevents[jank], scale = 0.3, colour = disabled and G.C.UI.TEXT_INACTIVE or get_color_from_saj_event(G.GAME.sajevents[jank]), shadow = not disabled}}
              }}
'''
match_indent = true


[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
            {n=G.UIT.R, config={align = "cm", minh = 0.45, maxw = 2.8, func = 'HUD_blind_reward'}, nodes={
              {n=G.UIT.T, config={text = localize('ph_blind_reward'), scale = 0.3, colour = G.C.WHITE}},
              {n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME.current_round, ref_value = 'dollars_to_be_earned'}}, colours = {G.C.MONEY},shadow = true, rotate = true, bump = true, silent = true, scale = 0.45}),id = 'dollars_to_be_earned'}},
            }},
'''
position = "after"
payload = '''
  {n=G.UIT.R, config={align = "cm"}, nodes={
                {n=G.UIT.T, config={text = localize('k_event'), scale = 0.3, colour = disabled and G.C.UI.TEXT_INACTIVE or G.C.WHITE, shadow = true}},
                {n=G.UIT.T, config={ref_table = G.GAME.blind, ref_value = "sajevent", scale = 0.3, colour = G.C.EDITION, shadow = true}}
              }},
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
function create_UIBox_blind_choice(type, run_info)
'''
position = "after"
payload = '''
local jank = 1
  if type == 'Small' then
    jank = 1
  elseif type == 'Big' then
    jank = 2
  else
    jank = 3
  end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''
                G.FUNCS.draw_from_hand_to_discard()
                if G.GAME.blind:get_type() == 'Boss' then
                    G.GAME.voucher_restock = nil
                    if G.GAME.modifiers.set_eternal_ante and (G.GAME.round_resets.ante == G.GAME.modifiers.set_eternal_ante) then 
                        for k, v in ipairs(G.jokers.cards) do
                            v:set_eternal(true)
                        end
                    end
                    if G.GAME.modifiers.set_joker_slots_ante and (G.GAME.round_resets.ante == G.GAME.modifiers.set_joker_slots_ante) then 
                        G.jokers.config.card_limit = 0
                    end
'''
position = "after"
payload = '''
                    generate_saj_for_curante()
'''
match_indent = false

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
    local bosses_used = {}
    for k, v in pairs(G.P_BLINDS) do 
        if v.boss then bosses_used[k] = 0 end
    end
    return {
'''
position = "after"
payload = '''
sajevents = {'Shop', 'Shop', 'Shop'},
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
    G.E_MANAGER:add_event(Event({
        trigger = 'immediate',
        func = (function()
            unlock_notify()
            return true
        end)
      }))
'''
position = "after"
payload = '''
print("Hi!")
generate_saj_for_curante()
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
function Game:update(dt)
'''
position = "after"
payload = '''
  if G.GAME and G.GAME.round_resets and G.GAME.round_resets.loc_blind_states then
  local shitfuck = "Shop"
  local functgfyhjftyj = function(n)
    local array = {Small = 1, Big = 2, Boss = 3}
    return array[n]
  end
  for k, v in pairs(G.GAME.round_resets.loc_blind_states) do
    if v == "Defeated" or v == "Current" or v == "Select" then
      shitfuck = G.GAME.sajevents[functgfyhjftyj(k)]
    end
  end
  G.GAME.current_sajevent = shitfuck
  end
  if G.GAME and G.GAME.blind and G.GAME.blind.loc_name then
  if G.GAME.blind.loc_name == 'Small Blind' then
    G.GAME.blind.sajevent = G.GAME.sajevents[1]
  elseif G.GAME.blind.loc_name == 'Big Blind' then
    G.GAME.blind.sajevent = G.GAME.sajevents[2]
  else
    G.GAME.blind.sajevent = G.GAME.sajevents[3]
  end
  end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'globals.lua'
pattern = '''
    --||||||||||||||||||||||||||||||
    self.STATES = {
'''
position = "after"
payload = '''
        LAB = 1478,
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''
              G.STATE = G.STATES.SHOP
'''
position = "at"
payload = '''
if G.GAME.current_sajevent == "Shop" then
G.STATE = G.STATES.SHOP
elseif G.GAME.current_sajevent == "Lab" then
G.STATE = G.STATES.LAB
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
        if self.STATE == self.STATES.SHOP then 
            self:update_shop(dt)
        end
'''
position = "after"
payload = '''
        if self.STATE == self.STATES.LAB then 
            self:update_lab(dt)
        end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''
    if state == G.STATES.SHOP then 
        ease_colour(G.C.DYN_UI.MAIN, mix_colours(G.C.RED, G.C.BLACK, 0.9))
'''
position = "after"
payload = '''
    elseif state == G.STATES.LAB then
        ease_colour(G.C.DYN_UI.MAIN, mix_colours(G.C.GREEN, G.C.BLACK, 0.9))
'''
match_indent = true

