[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
function Game:init_game_object()
'''
position = "after"
payload = '''
'''
match_indent = true