[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = 'cardarea.lua'
pattern = '''
(self.config.type == 'hand' and ({[G.STATES.SHOP]=1, [G.STATES.TAROT_PACK]=1, [G.STATES.SPECTRAL_PACK]=1, [G.STATES.STANDARD_PACK]=1,[G.STATES.BUFFOON_PACK]=1,[G.STATES.PLANET_PACK]=1, [G.STATES.ROUND_EVAL]=1, [G.STATES.BLIND_SELECT]=1})[state]) or
'''
position = "at"
payload = '''
 (self.config.type == 'hand' and ({[G.STATES.SHOP]=1, [G.STATES.LAB] =1,[G.STATES.TAROT_PACK]=1, [G.STATES.SPECTRAL_PACK]=1, [G.STATES.STANDARD_PACK]=1,[G.STATES.BUFFOON_PACK]=1,[G.STATES.PLANET_PACK]=1, [G.STATES.ROUND_EVAL]=1, [G.STATES.BLIND_SELECT]=1})[state]) or
'''
match_indent = true 


[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''
 G.GAME.current_round.used_packs = {}
'''
position = "after"
payload = '''
 LAB.merge_cost = LAB.merge_cost_reset
'''
match_indent = true 

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''
 G.CONTROLLER.locks.toggle_shop = true
'''
position = "after"
payload = '''
if LAB.in_lab then
    reset_merge()
    LAB.in_lab = false
end
'''
match_indent = true 
 
 [[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''
 if G.SETTINGS.current_setup == 'New Run' then 
'''
position = "after"
payload = '''
if LAB then
    print("LAB RESET!")
    LAB.save_merge_1 = nil
    LAB.save_merge_2 = nil
    LAB.save_suits_area = nil
    LAB.save_result = nil

    LAB.in_lab = false
end
'''
match_indent = true